### PR TITLE
feat(design): add nav-accordion-item component

### PR DESCRIPTION
**Pull request by lderrickable**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the new behavior?
A new `daff-nav-accordion-item` component was added for use in navigation contexts with nested accordion-items.

The plan is to use this for daff.io docs

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by xelaint** [comment]
I think `nested` may be a better property name for what this is trying to accomplish?

**Review by xelaint — CHANGES_REQUESTED** [review]
Goodwill Industries of Central Florida

**Comment by lderrickable** [comment]
I think I like `indent` better, since it directly describes what it's doing whereas `nested` does not. With `nested` we're claiming that we know exactly what everyone expects when an accordion item is nested. With `indent` it's very clear that the intention is. If you feel strongly about `nested` I'll change it though.

**Comment by lderrickable** [comment]
On second thought, maybe this is an imperative vs declarative thing. Could be that `nested` is better because it is declarative. I'm not sure

**Comment by lderrickable** [comment]
Ok, I just spoke to Damien about imperative vs declarative, and I do think that `indent` is probably the right call here for the reasons I previously stated.

**Review by damienwebdev — APPROVED** [review]
lgtm

**Pull request merged**
