### PR TITLE
Add tests to driver testing services

### PR DESCRIPTION
**Pull request by lderrickable**
add tests to driver testing services

## PR Checklist

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[x] Other: Testing
```

## What is the current behavior?
Additional tests are needed for driver testing services

Issue Number: https://github.com/graycoreio/daffodil/issues/110

## What is the new behavior?
Tests were added

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by lderrickable** [comment]
I'm going to put this on hold until the factory refactor is done

**Comment by damienwebdev** [comment]
@lderrickable does this PR need to be revisited/closed?

**Comment by lderrickable** [comment]
@damienwebdev I'm not exactly sure what you meant by https://github.com/graycoreio/daffodil/issues/110, but let me know if you want anything else done

**Comment by damienwebdev** [comment]
@lderrickable I think we'll need to clarify what the purpose of each method is before we go writing tests.

I think this PR, and that issue, are side-effects of a larger problem.

Specifically, we're not writing these tests before we write the code, so the tests are brittle and un-clear, and in some cases, there are many tests missing. 

When I wrote #110 I was looking at @daffodil/driver and thinking to myself that the driver's test suite is pretty thin, and even among the tests that already exist, the tests are fairly vague.

What I'd like to see done is a true "spec" written here (or in another issue if this issue is too vague) prior to the actual driver code being re-written in #147 or another similar issue. We can use the tests we write there as a conceptual as a starting point for the rest of driver.

**Comment by lderrickable** [comment]
can we push this to develop? It's better than no tests, right? Because right now these specs are empty in develop

**Comment by damienwebdev** [comment]
I'm going to close this as I don't think its relevant any longer.

**Pull request closed without merging**
