### PR TITLE
feat(navigation): add a testing module to mock out the DaffNavigation…

### PR DESCRIPTION
**Pull request by lderrickable**
…Facade in tests

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
Currently the end user needs to provide his/her own mock of the `DaffNavigationFacade` whenever it comes up in testing to avoid any interaction with ngrx store.

Fixes: N/A

## What is the new behavior?
`@daffodil/navigation/testing` now has a `DaffNavigationTestingModule` that provides a mocked version of the `DaffNavigationFacade` for you.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by lderrickable** [comment]
@damienwebdev added `DaffNavigationFacadeInterface`

**Comment by damienwebdev** [comment]
I think the code looks fine, I'm just torn on the value provided by the `MockFacade`. I wonder if we're being too opinionated on how to test components that utilize the facade. 

Most of the time, I'd imagine someone would want to test this component, I think they would care about how the facade is being utilized, which warrants a custom mock. 

I wonder if maybe we can only publish the facade interface, and let people mock against that instead?

**Comment by lderrickable** [comment]
With this, you can always decide what the facade returns. It just makes it so you don't need to write out:
```
export class MockDaffNavigationFacade implements DaffNavigationFacadeInterface {
  loading$: Observable<boolean> = new BehaviorSubject(false);
  tree$: Observable<DaffNavigationTree> = new BehaviorSubject(null);
  errors$: Observable<string[]> = new BehaviorSubject([]);
  dispatch() { }
}
```
every single time it shows up. Instead, you just import the DaffNavigationTestingModule, and go
```
let facade = TestBed.get(DaffNavigationFacade);
facade.tree$ = of(stubTree);
```
The initial value is just the initial value in the reducer:
```
const initialState: NavigationReducerState = {
  navigationTree: null,
  loading: false,
  errors: []
};
```

**Comment by damienwebdev** [comment]
@lderrickable in order to have a component use:

```ts
let facade = TestBed.get(DaffNavigationFacade);
facade.tree$ = of(stubTree);
```

You have to do this before the first `fixture.detectChanges()`; as there's where the `facade` properties become bound in the component.

And then, if I want to change the value later in the component, I can't do:

```ts
facade.tree$ = of(somethingElse);
``` 

Because I'd have to re-run `ngOnInit`. I for a while tried to make this work with BehaviorSubjects, as I think that's a decent opportunity for this since we can call `.next()` on a BehaviorSubject, but facades are typed `Observable<prop>` so unless we do some type juggling, we can't easily allow our end users to call:

```ts
facade.tree$.next(val);
```

**Comment by lderrickable** [comment]
You were right about the `BehaviorSubject`. The injection and typing works similarly to how `MockStore` is injected with rxjs tests where you type the navigationFacade as the mock, but you actually get the `DaffNavigationFacade` from the TestBed. Here is an example that works:
```
import { async, ComponentFixture, TestBed } from '@angular/core/testing';
import { StoreModule, Store } from '@ngrx/store';
import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { RouterTestingModule } from '@angular/router/testing';
import { By } from '@angular/platform-browser';

import * as fromSidebar from '../../../sidebar/reducers/index';
import { ToggleSidebar } from '../../../sidebar/actions/sidebar.actions';

import { LogoModule } from '../../../logo/logo.module';
import { DemoHeaderContainer } from './header.component';
import { DemoHeaderComponent } from '../../components/header/header.component';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { DaffNavigationTestingModule, DaffNavigationTreeFactory, MockDaffNavigationFacade } from '@daffodil/navigation/testing';
import { DaffNavigationFacade, DaffNavigationTree } from '@daffodil/navigation';

describe('DemoHeaderContainer', () => {
  let component: DemoHeaderContainer;
  let fixture: ComponentFixture<DemoHeaderContainer>;

  let store: Store<fromSidebar.State>;
  let navFacade: MockDaffNavigationFacade;
  let treeFactory: DaffNavigationTreeFactory = new DaffNavigationTreeFactory();
  let tree: DaffNavigationTree = treeFactory.create();

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [
        StoreModule.forRoot({}),
        RouterTestingModule,
        LogoModule,
        FontAwesomeModule,
        DaffNavigationTestingModule
      ],
      declarations: [
        DemoHeaderContainer,
        DemoHeaderComponent
      ],
      schemas: [
        CUSTOM_ELEMENTS_SCHEMA
      ]
    })
    .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(DemoHeaderContainer);
    component = fixture.componentInstance;
    store = TestBed.get(Store);
    spyOn(store, 'dispatch');
    navFacade = TestBed.get(DaffNavigationFacade);
    navFacade.tree$.next(tree);
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });

  describe('when [header-menu-button] is clicked', () => {
    it('should call store.dispatch with a ToggleSidebar action', () => {
      const sidebarButton = fixture.debugElement.query(By.css('[header-menu-button]')).nativeElement;
      sidebarButton.click();
      
      expect(store.dispatch).toHaveBeenCalledWith(new ToggleSidebar());
    });
  });

  describe('Testing the MockDaffNavigationFacade', () => {
    
    it('should be a tree when it is set to a tree', () => {
      component.navigationTree$.subscribe(tree => {
        expect(tree).not.toBeNull();
      });
    });
    
    it('should change to null when you want it to', () => {
      navFacade.tree$.next(null);
      component.navigationTree$.subscribe(tree => {
        expect(tree).toBeNull();
      });
    });
    
    it('should be a tree again when you set it to a tree', () => {
      navFacade.tree$.next(tree);
      component.navigationTree$.subscribe(tree => {
        expect(tree).not.toBeNull();
      });
    });
  });
});
```

**Pull request merged**
