### PR TITLE
feat(cart): add empty cart guard

### PR DESCRIPTION
**Pull request by lderrickable**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by griest024** [comment]
I think the name is a little misleading, it makes it sound like the guard will only pass if the cart _is_ empty.

**Comment by lderrickable** [comment]
hmm. I think of it as guarding against an empty cart

**Comment by griest024** [comment]
@lderrickable Can you add a jsdoc comment explaining it? I guess I'm okay with the name but I think the behavior should be explicitly mentioned.

**Comment by lderrickable** [comment]
sure, makes sense. Done

**Pull request merged**
