### PR TITLE
build(seo): publish SEO package

### PR DESCRIPTION
**Pull request by griest024**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

`@daffodil/seo` is private

## What is the new behavior?
`@daffodil/seo` is public

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by damienwebdev** [comment]
@griest024 can you add it to the README as well?

**Comment by griest024** [comment]
> @griest024 can you add it to the README as well?

not sure what you mean by "it" but I updated the readme

**Comment by damienwebdev** [comment]
Sorry, I wasn't clear at all with the commentary. I meant can you add the now published package to the root README.md

https://github.com/graycoreio/daffodil/blob/develop/README.md

**Review by damienwebdev — APPROVED** [review]
lgtm

**Pull request merged**
