### PR TITLE
feat(design): create compactable interface

### PR DESCRIPTION
**Pull request by xelaint**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
`compact` input is not normalized.

Part of: #763 

## What is the new behavior?
Create DaffCompactable` interface so the `compact` property will be consistent throughout @daffodil/design 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Review by damienwebdev — DISMISSED** [review]
lgtm

**Comment by damienwebdev** [comment]
@xelaint can you sign this commit?

**Comment by xelaint** [comment]
> @xelaint can you sign this commit?

@damienwebdev signed

**Review by damienwebdev — APPROVED** [review]
lgtm

**Pull request merged**
