### PR TITLE
feat(core): add XOR type for mutual exclusion typing

### PR DESCRIPTION
**Pull request by damienwebdev**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
Currently, we don't have any legible way to describe a Disjoint type. 

Fixes: N/A

## What is the new behavior?
This adds a new XOR type that we can use to describe our interfaces a bit better.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
Derived from https://github.com/microsoft/TypeScript/issues/14094#issuecomment-373782604

### CODE REVIEW

**Comment by yard2010** [comment]
Honest question - why is this closed and not merged? Can I do anything about it?

**Comment by griest024** [comment]
I don't remember exactly but I believe we didn't have a use case for it.

**Comment by griest024** [comment]
@damienwebdev Do you remember why this was closed? Were there problems with the type behavior?

@yard2010 The code is MIT licensed to feel free to use it somewhere else if you want. Just be sure to give proper credit (note the comment in the TS repo).

**Comment by yard2010** [comment]
This is embarrassing - I have just realised that this is not the official typescript repo! I got here from [this typescript issue](https://github.com/Microsoft/TypeScript/issues/14094) and I didn't understand I left the repo.  Anyway, thanks for the permission to use it and good luck with what you're doing, it looks fantastic.

**Comment by griest024** [comment]
> good luck with what you're doing, it looks fantastic.

Tell your friends 😁

**Comment by damienwebdev** [comment]
A comment here, because I came to this conclusion long ago. The XOR type is an anti-pattern that should instead be replaced with a discriminable union. You should "kind" your types with a string `kind` and discriminate on the kind. 

My XOR type works, but goes against what the typescript team is in favor of.

**Pull request closed without merging**
