### PR TITLE
[WIP] feat(cart): add a selector for whether the cart has a shipping method…

### PR DESCRIPTION
**Pull request by lderrickable**
… applied

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
Adds a selector for whether the cart has a shipping method applied (does this by checking if the shipping total is null). Added a field to the DaffCartFacade as well.

### CODE REVIEW

**Comment by griest024** [comment]
Can you not use the `hasShippingMethod` selector?

**Comment by lderrickable** [comment]
I was trying to differentiate between applied and available shipping methods, because both of those are on the cart

**Comment by griest024** [comment]
@lderrickable the selector is for applied shipping method:
```ts
const selectHasShippingMethod = createSelector(
    selectCartShippingInformation,
    shippingMethod => !!shippingMethod
  );
```

If its not working as you expect you might need to give it the same treatment that I gave to the has payment method selector.

**Comment by lderrickable** [comment]
@griest024 Oh, I see what you're saying now. I'll take a look. I think I should be able to use that instead

**Comment by lderrickable** [comment]
yea, my bad. I jumped the gun on this one. `hasShippingMethod` works fine. Closing this

**Pull request closed without merging**
