### PR TITLE
ci(design): add sass-lint to design builds

### PR DESCRIPTION
**Pull request by damienwebdev**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[x] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
Currently, we don't enforce code style constraints on our scss. 

Fixes: N/A

## What is the new behavior?
This enforces a code style constraint.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by xelaint** [comment]
can we add `empty line between blocks` as a rule? (https://github.com/sasstools/sass-lint/blob/master/docs/rules/empty-line-between-blocks.md)

**Comment by damienwebdev** [comment]
@xelaint would you want it to be `true` or `false`?

**Comment by xelaint** [comment]
@damienwebdev true

**Comment by lderrickable** [comment]
Those are some BIG tabs, but ok

**Comment by xelaint** [comment]
@lderrickable they look normal in vscode

**Pull request merged**
