### PR TITLE
feat(daffio): update daffio homepage

### PR DESCRIPTION
**Pull request by xelaint**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by xelaint** [comment]
@damienwebdev squashed

**Comment by damienwebdev** [comment]
@xelaint can the Magento logo be an SVG? Additionally, can the pwa-screens be a JPEG rather than a png?

**Comment by xelaint** [comment]
@damienwebdev
> @xelaint can the Magento logo be an SVG? Additionally, can the pwa-screens be a JPEG rather than a png?

For the pwa-screens, I have it as png so the background is transparent and takes on the container color the image is in. If I add a specified background color, how will it work with theming?

**Comment by xelaint** [comment]
@damienwebdev 98kbs, 53kbs, and 20kbs!

**Comment by damienwebdev** [comment]
@xelaint the svgs still contain base64 encoded images. Additionally, they need to be minified, once that's resolved.  I highly recommend https://github.com/svg/svgo.

**Comment by xelaint** [comment]
@damienwebdev removed base64 images from svgs

**Comment by xelaint** [comment]
@damienwebdev ready to be reviewed again!

**Comment by xelaint** [comment]
@damienwebdev ready to be re-reviewed.

**Comment by xelaint** [comment]
@damienwebdev no more changes! please re-review.

**Pull request merged**
