### PR TITLE
docs(design): update theme switch stackblitz example link

### PR DESCRIPTION
**Pull request by xelaint**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/develop/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
The current StackBlitz link that showcases theming is stale.

Fixes: N/A

## What is the new behavior?
The StackBlitz link is updated with package dependencies that are aligned with `@daffodil/design`

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by damienwebdev** [comment]
@xelaint added a diff here, looks like we need another example where we provide a custom theme.

**Comment by xelaint** [comment]
@damienwebdev added

**Comment by xelaint** [comment]
> @xelaint added a diff here, looks like we need another example where we provide a custom theme.

added

**Review by damienwebdev — APPROVED** [review]
lgtm

**Pull request merged**
