### PR TITLE
Add contributing docs for component padding/margin

### PR DESCRIPTION
**Pull request by lderrickable**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by damienwebdev** [comment]
@lderrickable can we move this into another document? Potentially something like docs/styling.md? Maybe we keep it inside libs/design?

**Comment by lderrickable** [comment]
@damienwebdev sure, though I don't think it should go in libs/design. It will mostly be applicable to commits to specific apps like foundation-demo or the minisite

**Comment by damienwebdev** [comment]
@lderrickable maybe under:

```
docs/styles/padding-and-margin.md
```

**Comment by lderrickable** [comment]
> @lderrickable maybe under:
> 
> ```
> docs/styles/padding-and-margin.md
> ```

I'm pretty sure you can link sections of readme files, so we could link a section of a styles.md. Would you still rather split them all into separate files?

**Comment by lderrickable** [comment]
Why is this frozen?

**Comment by damienwebdev** [comment]
@lderrickable I froze this waiting for @daffodil/design, it can be unfrozen now. I think a single file will be fine for now. If it becomes unwieldy, we can always revisit in the future.

**Comment by lderrickable** [comment]
made the file lowercase. Just need a reapproval

**Pull request merged**
