### PR TITLE
feat(all): fixup versions for lerna

### PR DESCRIPTION
**Pull request by damienwebdev**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
Currently, all of our versions are pinned per module. This is hard to manage.

Fixes: N/A

## What is the new behavior?
This shifts version management into `lerna`, you can set the version in `lerna.json`.

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

## Other information

### CODE REVIEW

**Comment by lderrickable** [comment]
I don't understand how this works, because it doesn't look like anything related to versioning is defined in lerna.json. It just has `"version": "0.0.0"`

**Comment by damienwebdev** [comment]
@lderrickable here's the explanation:

Lerna will manage the package version for us in `lerna.json`, but in order for builds to work properly, all the versions in the `package.json`'s must be setup properly.

Given that all the packages should be used together, I figure pinning them to `0.0.0` locally and the letting lerna manage the versions at release time makes the most sense.

You can see the version lerna will pin them to in `lerna.json`. I'll add release docs regarding this when we get to our first release.

**Comment by damienwebdev** [comment]
@xelaint as this impacts the design package's version, I'll need a review from @graycoreio/daff-design

**Comment by damienwebdev** [comment]
@xelaint @lderrickable squished, needs a re-review.

**Pull request merged**
