### PR TITLE
feat(cart): handle empty and null responses in Magento driver

### PR DESCRIPTION
**Pull request by griest024**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

- Magento responses that contain null or empty fields will cause the transformers to throw when passed
- Queries use incorrect parameters

## What is the new behavior?
- The drivers and cart transformer will check for `null` and `[]` responses and return `null` without invoking the transformer
- Queries now use the correct parameters

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by lderrickable** [comment]
I feel like the most complicated method is typically the driver call, so I think you should move the null checking part into the transformers when possible.

**Comment by griest024** [comment]
@lderrickable I was thinking that its not really the responsibility of the transformer to determine if the response needs to be transformed or not. Plus not all checks can be done inside the transformer and I wanted to keep it consistent where the check were done.

Moving the check inside the transformer would prevent some duplication of logic though; I'm open to that option. LMK what you think.

**Comment by lderrickable** [comment]
@griest024 I could also argue that transformers should be able to handle transforming any variation of the type of object they expect. I think null/undefined should always be considered by any service/function. I think this is why I don't like how magneto accepts arguments for graphQL calls. Passing null values makes a magento graphQL query fail. This is a little different because we control the inputs by the driver service into a transformer, but I still think as a rule a method should be responsible for handling a null/undefined input.

**Comment by griest024** [comment]
@lderrickable You've convinced me. That makes sense especially because TS allows `null` to be passed into the transformers.

**Comment by griest024** [comment]
@lderrickable Changed in [`24db473`](https://github.com/graycoreio/daffodil/pull/696/commits/24db473c7cba041db4725c9c3044fb4390025e8d). I added a check in all of the response transformers. Some drivers still needed a check.

**Pull request merged**
