### PR TITLE
feat(cart): update email with Magento shipping address update

### PR DESCRIPTION
**Pull request by griest024**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Fixes: N/A

## What is the new behavior?
- The shipping address update now updates the cart's email as well
- Changes the shipping and billing address updates to use compound mutations
- Changes all address update operations to conditionally send email update if email is set on the input address

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by lderrickable** [comment]
What happens if the email isn't provided? On the DaffPersonalAddress model, `email` is optional.

**Comment by griest024** [comment]
@lderrickable I guess it would fail. I'll conditionally send different queries based on the prescence of `email`.

**Comment by griest024** [comment]
@lderrickable changed

**Comment by lderrickable** [comment]
lgtm

**Pull request merged**
