### PR TITLE
ci(all): add code coverage reporting for all packages

### PR DESCRIPTION
**Pull request by griest024**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Fixes: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

### CODE REVIEW

**Comment by damienwebdev** [comment]
@griest024 this is still WIP? I don't see any changes in the output of code climate.

**Comment by griest024** [comment]
> @griest024 this is still WIP? I don't see any changes in the output of code climate.

yes it is, my bad. I forgot to mark it as draft

**Comment by xelaint** [comment]
@griest024 can this be closed?

**Comment by griest024** [comment]
> @griest024 can this be closed?

yes, the branch should remain for posterity though

**Pull request closed without merging**
