### PR TITLE
feat(tools-dgeni): remove internal properties from generated docs

### PR DESCRIPTION
**Pull request by lderrickable**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
Fields that are not part of the public API are shown in the generated docs.

## What is the new behavior?
Fields that are prefixed with an underscore and the angular lifecycle hooks are removed during docs generation.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by damienwebdev** [comment]
I like this idea, but maybe instead of trying to maintain a discrete set/matching underscores, we have a flag like `@private` somewhere in the method docs. I've noticed something similar when reading Angular internal docs and I think the premise is sound.

**Comment by lderrickable** [comment]
> I like this idea, but maybe instead of trying to maintain a discrete set/matching underscores, we have a flag like `@private` somewhere in the method docs. I've noticed something similar when reading Angular internal docs and I think the premise is sound.

Supposedly (according to the dgeni docs), there is a tag, `@private`, that can mark a field as private and filter it out with provided processors, but I couldn't get it to work. So I made it filter on `@docs-private`; i.e. any field that is labeled as `@docs-private` will not be added to the docs.

**Comment by lderrickable** [comment]
When looking into another issue, I learned that this is exactly how angular tags properties as private. They tag it with the custom tag "@docs-private" and add this tag to the list of supported tag definitions. I added this tag to our list of supported tag definitions.

**Comment by damienwebdev** [comment]
Can we then check the tag instead as opposed to searching the entire content for the string?

**Comment by lderrickable** [comment]
> Can we then check the tag instead as opposed to searching the entire content for the string?

yep, done

**Comment by damienwebdev** [comment]
Lgtm.

**Review by damienwebdev — APPROVED** [review]

**Pull request merged**
