### PR TITLE
feat(seo): add seo/state and update action pair

### PR DESCRIPTION
**Pull request by griest024**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

#1704

## What is the new behavior?
Adds a model that describes how an app feature can describe providing SEO info in response to specific actions

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by damienwebdev** [comment]
I think the basic concept here is fine, but I would like to see an example usage in another PR before merge. 

For example, how does this work with `title` vs. `meta` vs. `schema`, etc. Do we need to futher extend this action to support such mechanisms?

**Comment by griest024** [comment]
@damienwebdev #1709. The effects unit test kinda demonstrates it. I'll write an integration test and a guide as well

**Comment by griest024** [comment]
@damienwebdev added `Action` generic and canonical URL subtype

**Comment by griest024** [comment]
@damienwebdev ready for review

**Review by damienwebdev — APPROVED** [review]
lgtm

**Pull request merged**
