### PR TITLE
feat(daffio): create components overview page

### LINKED ISSUE #3329: [BUG] Daffio design components overview 404
# :bug: Bug report

## Current Behavior

`/docs/design/components` 404s

## Expected Behavior

`/docs/design/components` does not appear in the nav list

### PR DESCRIPTION
**Pull request by xelaint**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/develop/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Fixes: #3329 

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

### CODE REVIEW

**Comment by xelaint** [comment]
@griest024 can you help me link up the cards to the doc list data?

**Comment by griest024** [comment]
@xelaint done

**Comment by xelaint** [comment]
@griest024 form is using the error message component's description, and all the components under form are not shown in the cards. Would this be fixed if we move these components to their own subpackages?

Screen Shot 2024-11-02 at 9 51 04 AM
Screen Shot 2024-11-02 at 9 50 50 AM

**Comment by griest024** [comment]
@xelaint oh yeah it would. I can also do some hard coding to fix it in the short term

**Comment by xelaint** [comment]
> @xelaint oh yeah it would. I can also do some hard coding to fix it in the short term

hardcoding might be better for now? since all of these components need to be redone.

**Comment by griest024** [comment]
@xelaint done

**Pull request merged**
