### PR TITLE
feat(daffio): create packages sidebar

### PR DESCRIPTION
**Pull request by xelaint**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/develop/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
No specific sidebar for packages.

Part of: #2682 

## What is the new behavior?
There is a packages sidebar now that should be rendered within the `/packages/..` pages.

TODO:
- [ ] Updating the visibility of sidebar headers and footer depending on breakpoints.
- [ ] Switching out sidebar content depending on which activator is pressed/clicked on. There is always a top level sidebar content, which contains the same content as the header. There can be sidebars within a page and that content needs to display the correct information. Currently, the side fixed sidebar in each package page is showing the header content info instead of the package content info.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by griest024** [comment]
@xelaint lmk what you think about the updated behavior

**Comment by xelaint** [comment]
Screen Shot 2024-01-19 at 4 25 07 PM

Screen Shot 2024-01-19 at 4 25 16 PM

@griest024 The sidebar header and footer is visible on the `/api` page (first ss), but not on the `guides/..` pages.

I feel like splitting up the sidebars into three separate named views is part of issue?

**Comment by griest024** [comment]
@elainoo what should the header and footer be in the `/guides/...` routes? I assumed you didn't want them since there was nothing defined in the [named views for these routes](https://github.com/graycoreio/daffodil/blob/91ab4fc10ae24c9d2c86386f6303c30d9194b4be/apps/daffio/src/app/app-routing.module.ts#L60).

**Comment by griest024** [comment]
@xelaint I added the header and footer, LMK if this is what you want

**Comment by xelaint** [comment]
Screen Shot 2024-01-23 at 10 48 34 AM

@griest024 Close, but the package sidebar header and footer should be hidden while the package sidebar is still in `side-fixed` mode.

**Comment by griest024** [comment]
@xelaint changed. Note that the "get started" footer shows for the packages list sidebar when opened as the "content" sidebar, IDK if this is what you want.

There's also a failing test that I need to look at later but the implementation is ready for you to look at.

**Comment by xelaint** [comment]
@griest024 I think this PR is good to go for now, but questions for future implementation:

1. What happens when I need a different content sidebar for i.e. `daff.io/docs/design`. Are we going to set different content kinds for each inner sidebar? How will the sidebar content render correctly depending on which page we're on?

**Comment by griest024** [comment]
@xelaint would `daff.io/docs/design` have its own route config definition? If so, it can just define the changed sidebar components in its `data.namedViews`. More deeply nested configs will overwrite parents' configs. The overall collection of named views will be merged together so only keys (`sidebarcontent`, `sidebarheader`, etc.) that are specified by the child will overwrite parent fields.

**Pull request merged**
