### PR TITLE
feat(design): add toast component

### PR DESCRIPTION
**Pull request by xelaint**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/develop/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
The `@daffodil/design` package is missing a toast component that can be used to display time-sensitive notifications that are related to application level information.

Part of: #1948 

## What is the new behavior?
Toast component that is displayed at the top-level of the interface that is used to communicate time-sensitive notifications that are related to application level information.

TODO:
- [x] Make `duration` work
- [x] Implement CDK Overlay
- [x] Type on button doesn't seem to be working in toast
- [ ] Support anchor links as actions
- [x] Is there a way to change position strategy depending on screen size?
- [x] Can we display the newly opened toast on top of the last one instead of after on the bottom?
- [x] Can we support configurable positions? (`DaffToastHorizontalPosition` and `DaffToastVerticalPosition`)
- [x] Documentation
- [x] Tests

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by xelaint** [comment]
- [x] Type on button doesn't seem to be working in toast
~~- [ ] Support anchor links as actions~~
- [x] Is there a way to change position strategy depending on screen size?
- [x] Can we display the newly opened toast on top of the last one instead of after on the bottom?
- [x] Can we support configurable positions?
- [x] Documentation 
- [x] When there are actions in the toast, there should be a role of `alertdialog`
- [x] When there are two components that reference toasts, use the same toastservice.

**Comment by damienwebdev** [comment]
From a discussion between @xelaint and myself, we decide that the toast should not, by default, hand down "status" to its child buttons.

**Comment by xelaint** [comment]
- [x] How to set dismissible? (close button is shown when dismissible is set to true)
- [x] HostListener for keydown escape doesn't work. I think we need to implement focus trapping, specifically only if it's dismissible

**Comment by xelaint** [comment]
- [x] Implement a focus stack between modal-like elements, only if there are actions. (`DaffFocusStackService`)
- [x] Change toasts so that they render when the last one is either cleared or duration-removed, not clearing immediately. The filter is in the render layer, not the data layer.
- [x] Implement focus trap on toasts with actions.
- [x] Implement dismissible on toasts via data/configuration

**Comment by xelaint** [comment]
TODO:
- [ ] Tests

**Comment by xelaint** [comment]
@damienwebdev Need you to review the updates I made to the `size` property within `DaffToastAction`, and add tests.

**Review by griest024 — APPROVED** [review]

**Pull request merged**
