### PR TITLE
chore(all): upgrade angular to v12

### LINKED ISSUE #1883: [FEAT] Upgrade to Angular 13
# :page_facing_up: Feature Request

TODO

- [x] Update Peer Dependencies to Angular 13
- [x] Verify Node Versions - #2013 
- [x] Verify Universal Deployments on Vercel
- [x] Fix Builds - #2013 
- [x] Fix Tests - #2013 
- [x] Release Daffodil

### PR DESCRIPTION
**Pull request by griest024**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[x] Other... Please describe: angular upgrade
```

fixes #1883 

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

Upgrade to angular v12

## Other information

### CODE REVIEW

**Comment by griest024** [comment]
draft while some CI bugs are worked out

**Comment by griest024** [comment]
`ngcc` is not automatically run during tests now, it must be manually run.

**Comment by damienwebdev** [comment]
Superseded by #2013

**Pull request closed without merging**
