### PR TITLE
[WIP] feat(cart): add magento driver

### PR DESCRIPTION
**Pull request by griest024**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
No Magento support for the cart package.

Fixes: #537 

## What is the new behavior?
Magento support for the cart package.

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

- Adds necessary driver interfaces for transformers
- Adds new cart service driver

## Other information

### CODE REVIEW

**Comment by griest024** [comment]
Just wanted to see if I'm on the right track here and discuss some potential problems. The transformer tests are just stubs at the moment.

In particular, I wanted to talk about the transformers. It seems to me that we would always want the transformations to be reversible. Its tedious to maintain multiple transformers that implement the same transformation in both directions.

My idea is to provide a simple API of operations to transformers for defining tranformations in such a way that its reversible. Most of the time its a simple copy operation from one key to another, which could be easily reversed.

**Comment by damienwebdev** [comment]
@griest024 this is in the right direction. I have to write a spot of code for Magento to address some CORS errors so that I can do an acceptance test of whether this actually works, but the idea here looks pretty good.

**Comment by damienwebdev** [comment]
In terms of the invertible transformers, the idea seems solid in practice, but I can't quite see a use-case for it yet.

**Comment by griest024** [comment]
> In terms of the invertible transformers, the idea seems solid in theory, but I can't quite see a use-case for it yet.

Well it looks like you don't have many interface methods that actually mutate DB data yet but I assume that you would at some point to provide full featured interaction with the platforms. In this case, you would almost always need to convert daffodil models into platform-specific models.

**Comment by damienwebdev** [comment]
@griest024 Ah, I see what you're getting at. The issue is actually quite broad, and I hadn't even considered it yet. 

We'll need (for essentially every driver call), a transformation in both directions. It's actually almost universal for every driver call. Give me some time to iron out a proposal for exactly how this could theoretically work.

**Comment by lderrickable** [comment]
Just looking at this now. I don't understand why we would ever directly change data that were magento model types. We only ever need to transform into magento requests and out of magento responses. Maybe I'm missing something?

**Comment by lderrickable** [comment]
Also, I was looking into generic tokens, and as far as I can tell, they don't actually enforce strong typing. I'm not super familiar with how angular injects services through injection tokens, but I don't think it actually has a way to check the typing. I tried this and the build still passed:
```
@NgModule({
  imports: [
    CommonModule
  ]
})
export class DaffNavigationMagentoDriverModule {
  static forRoot(): ModuleWithProviders<DaffNavigationMagentoDriverModule> {
    return {
      ngModule: DaffNavigationMagentoDriverModule,
      providers: [
        {
          provide: DaffNavigationDriver,
          useExisting: DaffMagentoNavigationTransformerService      <-------------------
        },
        {
          provide: DaffNavigationTransformer,
          useExisting: DaffMagentoNavigationTransformerService
        }
      ]
    };
  }
}
```

**Comment by griest024** [comment]
@lderrickable Using the example of setting shipping information, the [request payload](https://devdocs.magento.com/redoc/2.3/guest-rest-api.html#operation/checkoutGuestShippingInformationManagementV1SaveAddressInformationPost) needs the address in the form of a Magento `AddressInterface`. Assuming Daffodil (or code that leverages Daffodil) handles the collecting of the customer's shipping address, it will necessarily require the transformation of a `DaffAddress` or `DaffCartAddress` into a Magento `AddressInterface`.

I assume this is what you mean when you say "transform into magento requests". This is one of the use cases I was considering when I suggested the invertible transformers. It seems to me that most, if not all, mutable requests (that is, POST and PUT) will require transforming some Daffodil models into platform-specific models.

**Comment by lderrickable** [comment]
@griest024 I think I see what you mean. In the shipping address example you gave, you mean that when updating the cart with an address we would need to send something like `updateShippingAddress(cartId, address)`, which would return a cart that has an address on it. So if we made just an address transformer, we could use it both ways to transform back and forth between daffodil and magento addresses. Is that right?

**Comment by griest024** [comment]
@lderrickable that's correct.

**Pull request closed without merging**
