### PR TITLE
feat(category,driver,product): centralize URI truncation regex

### PR DESCRIPTION
**Pull request by griest024**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Review by damienwebdev — DISMISSED** [review]
Lgtm, although there may be a missing dep failing the build.

**Comment by damienwebdev** [comment]
@griest024 can you submit a PR with this use case in external router?

**Comment by griest024** [comment]
@damienwebdev I can but its not a specific use-case. Its just that in order for the testing driver to meet the spec that was outlined in the docs, it needs to be able to truncate URIs.

**Comment by griest024** [comment]
@damienwebdev I changed URI truncation to use a function, since its much cleaner and doesn't force app devs to rely on regex if they don't want to

**Comment by lderrickable** [comment]
lgtm

**Pull request closed without merging**
