### PR TITLE
Remove dependency on foundation from foundation-demo

### PR DESCRIPTION
**Pull request by xelaint**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[x] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by damienwebdev** [comment]
> @damienwebdev @lderrickable This is just initial changes to the design package. I will fix the rest of the broken styles in separate PRs.

Let's keep them all in this PR.

**Comment by xelaint** [comment]
> > @damienwebdev @lderrickable This is just initial changes to the design package. I will fix the rest of the broken styles in separate PRs.
> 
> Let's keep them all in this PR.

Ready for review. Cart page styles is taken care of in #103 and I want to wait for #97 to be merged before making any changes to checkout styles.

**Comment by lderrickable** [comment]
If you look at the product page at smaller than 450px, the inner elements stop resizing and they overflow off the page

**Comment by xelaint** [comment]
> If you look at the product page at smaller than 450px, the inner elements stop resizing and they overflow off the page

@lderrickable fixed, ready for review

**Pull request merged**
