### PR TITLE
feat(daffio): add now.sh builds to daffio

### PR DESCRIPTION
**Pull request by damienwebdev**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[x] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
Currently, the daffio site isn't deployed anywhere, so reviewing can only be done locally. 

Fixes: N/A

## What is the new behavior?
This adds PR-preview builds so that we can deploy changes to now.sh on every PR build. 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by damienwebdev** [comment]
Hello!

**Comment by lderrickable** [comment]
lgtm

**Comment by lderrickable** [comment]
Oh whoops. I forgot you were going to make more changes

**Comment by lderrickable** [comment]
lgtm

**Pull request merged**
