### PR TITLE
refactor(daffio): restructure docs and api files

### PR DESCRIPTION
**Pull request by xelaint**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
The guides / api structure is confusing and should not need to be nested within the main `docs` folder. Some components used in `guides` can also be used in `api`. There are a few unnecessary components.

Part of: #1432

## What is the new behavior?
I had a hard time figuring out how I can split this into different PRs, so I just lumped it into one for now. These are the updates that were made:

1. Move `api-docs` folder out of `docs` and rename it to`api`
2. Move `guide-docs` folder out of `docs` and rename it to `guides`
3. Make `daffio-guide-viewer` and `daffio-guide-table-of-contents` components into `daffio-doc-viewer` and `daffio-doc-table-of-contents` so they can be used for `api` and `guides` pages.
4. `docs` folder now has all of the shared components/models/resolvers/services/factories for guides and api.
5. `daffio-guide-nav` is renamed to `daffio-guides-nav-tree`
4. Change `views` to `pages`
5. Remove `daffio-api-doc` component since the content in it can just be rendered in `api-page`

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

## Other information

### CODE REVIEW

**Comment by lderrickable** [comment]
The sidebar doesn't work on any api page, and the api pages aren't displayed correctly.

Also, the api-list page has changed where the doc type is above the doc name instead of on the left of it (this wasn't listed as an intended change).

**Comment by xelaint** [comment]
> The sidebar doesn't work on any api page, and the api pages aren't displayed correctly.
> 
> Also, the api-list page has changed where the doc type is above the doc name instead of on the left of it (this wasn't listed as an intended change).

The sidebar doesn't show up on the api page in develop at all. I'm not sure what I did to the templates to have it show though.

Accidentally removed the styles to display the doc type correctly. Added it back in.

**Comment by xelaint** [comment]
@lderrickable okay, fixed the sidebar issue. Api page doesn't have a table of contents, so it was throwing an error.

**Review by damienwebdev — APPROVED** [review]
lgtm

**Pull request merged**
