### PR TITLE
fix(design): fix bug where qty-dropdown had no validation

### PR DESCRIPTION
**Pull request by lderrickable**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

Fixes: https://github.com/graycoreio/daffodil/issues/295

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by damienwebdev** [comment]
@lderrickable I don't think these changes make too much sense. Firstly, this component is super awkward and requires the use of dom-selectors. I think this component needs to be refactored to implement the [ControlValueAccessor](https://angular.io/api/forms/ControlValueAccessor). 

I also think that it makes more sense to prevent bad inputs (actually blocking the change of the value) instead of not emitting on bad changes.

**Comment by lderrickable** [comment]
ok. I don't think we should do the refactor right now, because we agreed to table most design changes with `v0.0.2`. 

I'll look into the other changes though

**Comment by lderrickable** [comment]
on second thought, I do actually block the change of the value as well as not emit any changes. But in demo, you're still going to run into the problem where if the user enters "-1" they can still add the product to the cart unless demo uses the "valid" flag.

**Comment by damienwebdev** [comment]
Closing in favor of #330

**Pull request closed without merging**
