### PR TITLE
feat(product): default filters to `{}` in collection adapter

### PR DESCRIPTION
**Pull request by griest024**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/develop/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

`selectProductCollectionFilters` can return `null` or `undefined`

## What is the new behavior?
`selectProductCollectionFilters` adheres to the strict typing and only returns truthy values

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by griest024** [comment]
@damienwebdev or should this be a default value in the adapter?

**Review by damienwebdev — CHANGES_REQUESTED** [review]
This should probably be in the adapter. There's no good reason for it to be `null`.

**Comment by griest024** [comment]
> This should probably be in the adapter. There's no good reason for it to be `null`.

done

**Review by damienwebdev — APPROVED** [review]
lgtm

**Pull request merged**
