### PR TITLE
chore(deps): update dev dependencies to close vulnerability warnings

### PR DESCRIPTION
**Pull request by damienwebdev**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[x] Other... Please describe: chore
```

## What is the current behavior?
We get some warnings about various vulnerabilities from NPM (only related to dev deps). 

Fixes: N/A

## What is the new behavior?
No more warnings.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by damienwebdev** [comment]
Closes:

https://github.com/graycoreio/daffodil/pull/1561
https://github.com/graycoreio/daffodil/pull/1563
https://github.com/graycoreio/daffodil/pull/1509
https://github.com/graycoreio/daffodil/pull/1507
https://github.com/graycoreio/daffodil/pull/1506
https://github.com/graycoreio/daffodil/pull/1453
https://github.com/graycoreio/daffodil/pull/1395
https://github.com/graycoreio/daffodil/pull/1328

**Review by griest024 — APPROVED** [review]
there are still some security warnings but it does seem better for sure

**Comment by damienwebdev** [comment]
@griest024 the remaining alerts are due to angular versions -- which can be handled by a different dep upgrade. I'm also going to rebase this into more succinct commits as well once approved.

**Comment by damienwebdev** [comment]
Needs @lderrickable review.

**Review by lderrickable — DISMISSED** [review]

**Review by griest024 — APPROVED** [review]

**Pull request merged**
