### PR TITLE
feat(order): split state into separate package

### PR DESCRIPTION
**Pull request by griest024**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Fixes: N/A

## What is the new behavior?
- Moves the `@daffodil/driver` package to `@daffodil/driver/magento/2.4.0` in preparation for the 2.4.1 driver
- Moves all the state stuff to a new `@daffodil/order/state` package.
- No longer imports the state module into the main module.
- Providing of the guard redirect token is now done in the state module.
- The driver interfaces were moved to the `@daffodil/order/driver` package.

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

Change imports of state stuff to `@daffodil/order/state`. The state module must now be imported separately.

Import the Magento driver from `@daffodil/driver/magento/2.4.0`.

Import driver interfaces and tokens from `@daffodil/order/driver`.
## Other information

### CODE REVIEW

**Comment by damienwebdev** [comment]
I think that the errors (currently in the root) are both driver errors, and should be in `@daffodil/order/driver`.

**Comment by griest024** [comment]
Agreed

**Comment by griest024** [comment]
@damienwebdev done

**Review by damienwebdev — APPROVED** [review]
lgtm

**Pull request merged**
