### PR TITLE
feat(category): add meta_name and meta_description to DaffCategory

### PR DESCRIPTION
**Pull request by lderrickable**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the new behavior?
Added meta fields to `DaffCategory`.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by griest024 — APPROVED** [review]

**Comment by damienwebdev** [comment]
@lderrickable shouldn't this impact the in-memory driver as well?

**Comment by lderrickable** [comment]
> @lderrickable shouldn't this impact the in-memory driver as well?

Yes, but that's covered by the factory changes

**Comment by damienwebdev** [comment]
Indeed.

**Review by damienwebdev — APPROVED** [review]
Lgtm

**Pull request merged**
