### PR TITLE
fix(tools-dgeni): make types for properties HTML compatible

### PR DESCRIPTION
**Pull request by lderrickable**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
The docs generated by dgeni aren't compatible with HTML because angle brackets (`<`, `>`) get processed by the angular `innerHtml` injector as HTML elements rather than strings.

Fixes: https://github.com/graycoreio/daffodil/issues/1095

## What is the new behavior?
The angle brackets in types are replaced with their string equivalents (`&lt;`, `&gt;`) during docs generation.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by griest024 — APPROVED** [review]
nice

**Comment by damienwebdev** [comment]
Needs rebase.

**Comment by lderrickable** [comment]
> Needs rebase.

rebased

**Review by griest024 — APPROVED** [review]

**Review by damienwebdev — APPROVED** [review]
lgtm

**Pull request merged**
