### PR TITLE
feat(tools): add eslint shareable config

### PR DESCRIPTION
**Pull request by griest024**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

Fixes: #1309 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
The only rule not copied from the root config is the import order, as that is only relevant to this project.

### CODE REVIEW

**Comment by damienwebdev** [comment]
Is there a way to get our rules to pull from this one natively so that there's only one config?

**Comment by griest024** [comment]
@damienwebdev we can point npm to a file: `"@daffodil/eslint-config": "file:tools/eslint/config",`. Eslint might support direct file links as well so we can bypass npm entirely

**Comment by griest024** [comment]
@damienwebdev updated

**Review by damienwebdev — APPROVED** [review]
lgtm

**Pull request merged**
