### PR TITLE
feat(daffio): update `/guides` path to `/packages`

### PR DESCRIPTION
**Pull request by xelaint**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/develop/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
The current path for packages is `/guides`. This is inaccurate as `/guides` should be reserved for the actual guides documentation. Packages documentation should be filed under `/packages` and `/packages/..`

Part of: #2682 

## What is the new behavior?
Updated the names of components related to packages to reflect that. Updated the `/guides` paths to `/packages`

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by xelaint** [comment]
@griest024 which docs files do I need to update to actually change the generated urls for packages to `/packages/..` (i.e. `/packages/cart`). It's currently still `/guides` since I'm not sure which ones to edit.

**Comment by griest024** [comment]
@xelaint should just be [this one](https://github.com/graycoreio/daffodil/blob/develop/tools/dgeni/src/transforms/daffodil-guides-package/processors/generateGuideList.ts#L14), LMK if thats not sufficient

**Comment by xelaint** [comment]
> @xelaint should just be [this one](https://github.com/graycoreio/daffodil/blob/develop/tools/dgeni/src/transforms/daffodil-guides-package/processors/generateGuideList.ts#L14), LMK if thats not sufficient

@griest024 just changing that line doesn't work. The package cards end up being empty.

**Comment by griest024** [comment]
@xelaint I'll take a look

**Comment by griest024** [comment]
@xelaint I pushed a change, LMK how this works for you

**Comment by xelaint** [comment]
@griest024 ready for review

**Review by griest024 — APPROVED** [review]

**Pull request merged**
