### PR TITLE
feat(seo): add a service for managing description meta tags

### PR DESCRIPTION
**Pull request by lderrickable**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the new behavior?
Adds a service for managing description meta tags, which are used by search engines to display the descriptions of each search result.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by griest024 — COMMENTED** [review]
Do you think its worth adding a spec for the meta tag behavior when changing pages? I don't know if its likely to be a problem but it might be worth it since its the behavior that breaks with the Angular `Meta` service.

**Comment by lderrickable** [comment]
> Do you think its worth adding a spec for the meta tag behavior when changing pages? I don't know if its likely to be a problem but it might be worth it since its the behavior that breaks with the Angular `Meta` service.

I'd say that's already covered. The problem with the Angular `Meta` service is that when you call `addTag` twice, it will add an additional `meta` tag. So you'd need to call the `Meta.removeTag` function, then the `Meta.addTag` whenever you navigated to a different page. But this scenario is covered by the `when the description meta tag exists, it should update the existing meta element` test. When you navigate to a new page, it will upsert the meta tag rather than adding it.

**Review by griest024 — DISMISSED** [review]

**Review by griest024 — CHANGES_REQUESTED** [review]
Can you reimplement this by relying on the `Meta` service?

**Comment by damienwebdev** [comment]
Closing as it appears that https://github.com/angular/angular/issues/42700 is a real bug in Angular and the `upsert`/`remove` behaviors created here can be replicated with features of the original `Meta` service of Angular.

https://stackblitz.com/edit/angular-ivy-zzejke?file=src%2Fapp%2Fapp.component.ts

Is a working example of such code.

A future PR for such a service should outline a better, more general Meta service with a more thought-out API than the original Angular Service.

**Pull request closed without merging**
