### PR TITLE
fix(all): the typescript upgrade needs the tsconfig to be upgrade to …

### PR DESCRIPTION
**Pull request by lderrickable**
…es2018

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
This error occurs (https://github.com/microsoft/TypeScript/issues/29465) because of the recent typescript upgrade (https://github.com/graycoreio/daffodil/pull/1585).

You can see this error if you try to run the demo app.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by damienwebdev** [comment]
What error are you seeing in demo?

**Review by griest024 — APPROVED** [review]

**Comment by griest024** [comment]
I've seen this error before

**Comment by griest024** [comment]
> What error are you seeing in demo?

FWIW I reproed it

**Comment by lderrickable** [comment]
> What error are you seeing in demo?

microsoft/TypeScript#29465

**Pull request closed without merging**
